---
- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: # linux-2 ami image
      keypair: # pem file name
      subnetid: # subnet id
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
  tasks:
    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
         aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: # whatever name you want
         instance_tags:
            Name: # whatever name you want
         vpc_subnet_id: "{{ subnetid }}"
         assign_public_ip: yes
      register: ec2
